version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-container
    environment:
      MONGO_INITDB_DATABASE: challenge-simpli-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  mongodb_data:
