import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import Header from './components/ui/Header/Header'
import AppContainer from './components/containers/AppContainer/AppContainer'
import { ProductProvider } from '@/context/ProductContext'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ProductProvider>
        <body className={roboto.className}>
          <AppContainer>
            <Header />
            {children}
          </AppContainer>
        </body>
      </ProductProvider>
    </html>
  )
}
